### PR TITLE
Improvements to source map handling in gulp

### PR DESCRIPTION
**Pull request by rhendric**

### CODE REVIEW

**Comment by ChadKillingsworth** [comment]
Your pull request doesn't have a description, list the options you are using, tell me what you have tried or even what problem you are attempting to solve. Nor does it have any tests associated with it.

**Comment by rhendric** [comment]
Details are in the commit messages; they're pretty option-agnostic. You got me on the tests though; I'll add some.

**Comment by ChadKillingsworth** [comment]
While I appreciate the effort, I'm going to need a lot more detail:

 1. How did you discover the issue? What were you trying to do?
 2. You mention composing source maps. This implies a chain of transformations. Listing a specific, reproducible sample, show how you believe that transformation chain should occur.
 3. Is this the behavior other compilers (like uglifyjs) uses? Or is this behavior specific to gulp plugins?
 4. Are there edge cases, such as what happens when only one in a set of input files has an input source map? How does this account for code which uses absolute path imports vs relative?
 5. What options are you using? Are you using the base option of gulp.src? How does the output differ when the input files are at different relative depths to the project root?

Ultimately I need to determine if what you propose is the correct behavior. If so, is this something that should be solved in the gulp plugin or in the core compiler itself? Or is it simply a matter of properly mapping paths for the input files and sourcemaps so that the compiler produces the correct output.

While I can look at your code samples, I have no problem statement against which to evaluate the implementation and verify it is doing what it is intended.

**Comment by rhendric** [comment]
Fair enough! Sorry for being terse; here are more words.

There are two issues here, hence the two commits. The first is more straightforward: with this `gulpfile.js`

```js
var gulp = require('gulp');
var closureCompiler = require('google-closure-compiler').gulp();
var sourcemaps = require('gulp-sourcemaps');

gulp.task('default', function () {
    return gulp.src('foo.js')
        .pipe(sourcemaps.init())
        .pipe(closureCompiler())
        .pipe(sourcemaps.write({debug: true}))
        .pipe(gulp.dest('out'));
});
```

you will see this debug output:

```
gulp-sourcemap-write: No source content for "/foo.js". Loading from file.
gulp-sourcemap-write: source file not found: /foo.js
```

even though `foo.js` exists in the project directory. The desired behavior of course is no error message and the source content successfully loaded and embedded in the map. The problem is the absolute path, as can be seen by decoding the source map embedded in `out/compiled.js`:

```json
{"version":3,"file":"compiled.js","lineCount":1,"mappings":"AAAAA,OAAAC,IAAA,CAAY,eAAZ;","sources":["/foo.js"],"names":["console","log"],"sourceRoot":"/source/","sourcesContent":[]}'
```

As I mentioned in the commit message, this is a regression introduced in c332988, and doesn't appear to be a problem with the core Closure compiler—garbage in, garbage out, after all. I'm not familiar with the problem you solved with c332988, but I assume you had your reasons so I attempted the least invasive fix.

---

The second issue—arguably a feature request, although here you could make a case for this being an issue with the core Closure compiler—involves composing source maps from multiple transformations. Here's my project's use case:

```js
var gulp = require('gulp');
var livescript = require('gulp-livescript');
var closureCompiler = require('google-closure-compiler').gulp();
var sourcemaps = require('gulp-sourcemaps');

gulp.task('default', function () {
    return gulp.src('foo.ls')
        .pipe(sourcemaps.init())
        .pipe(livescript())
        .pipe(closureCompiler())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('out'));
});
```

And here is the decoded source map produced by this pipeline:

```json
{"version":3,"file":"compiled.js","lineCount":1,"mappings":"AAAC,SAAQ,EAAE,CACTA,OAAAC,IAAA,CAAY,eAAZ,CADS,CAAV,CAADC,KAAA,CAEQ,IAFR;","sources":["/foo.js"],"names":["console","log","call"],"sourceRoot":"/source/","sourcesContent":[]}
```

As you can see, while I'm starting with a LiveScript file `foo.ls`, the source map refers to an intermediate JavaScript file `foo.js`, which 1) isn't the true source file I want to see while debugging, and 2) doesn't even exist on disk anyway, thanks to the gulp streaming magic. What I would like to end up with is a source map that points back to the original `foo.ls`. I can do this by composing the source map generated by the LiveScript plugin with the source map generated by the Closure plugin.

This is also a thing that the Closure compiler could do itself, since the input source maps are streamed to it. I believe UglifyJS2 takes this approach, but I think it's somewhat rare for code transformers, gulp or otherwise, to be this thoughtful. I could be mistaken about that. Anyway, if that's your preferred approach, here's a wrinkle (which my code addresses). Amend the gulpfile to write the intermediate JavaScript to disk:

```js
gulp.task('default', function () {
    return gulp.src('foo.ls')
        .pipe(sourcemaps.init())
        .pipe(livescript())
        .pipe(gulp.dest('generated_js'))
        .pipe(closureCompiler())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('out'));
});
```

and now the file that Closure thinks its receiving has path `generated_js/foo.js`, but the source map that it receives still calls itself just `foo.js` in its `"file"` property. A correct implementation has to ignore the `"file"` property in the source map when matching up sources with Closure's own source map, which refers to `generated_js/foo.js`.

To answer your question about edge cases, in the case that only some of the input files come with a source map—_e.g._, `A.ls` → `A.js`, `A.js` + `B.js` → `compiled.js`—I would want the source map for `compiled.js` to refer to `A.ls` and `B.js`—in other words, the true inputs to the entire pipeline. This is, to the best of my knowledge, what would happen with the code I submitted.

By ‘code imports’ do you mean `goog.require` and the like? I think those are irrelevant to how source maps are generated, except inasmuch as Closure uses them to figure out what files to include. Closure should continue to use whatever absolute/relative logic it uses to figure that out, and simply refer in its produced source maps to accurate paths of the files that it chooses. (`/foo.js` is not an accurate path because `foo.js` doesn't sit in the root of my file system, but `foo.js` or `/home/rhendric/projects/blah/foo.js` are both fine with me).

---

As you can see, in both of these issues I'm using basically no special configuration and very boring use cases. Both issues persist regardless of whether there are one or many input files, and whether they are located in their own directories or in the project root. You should be able to reproduce both issues easily and investigate any other combinations you think of.

If this all makes sense to you, I'll start writing up those tests for the above and add them to the PR.

**Comment by ChadKillingsworth** [comment]
Perfect - thanks! That's exactly what I needed.

For the relative path issue, all the input files are converted to absolute paths anchored to the project root. This is because in source, you see statements such as:

```js
import bar from '/path/segment/foo';`
```

The input file path needs to match that as well. Thankfully, vinyl takes care of remapping that back to a relative root - but obviously I forgot about the source map references or assumed that `applySourceMap` took care of it for me.

The fix for that though should be in the [json-to-vinyl.js](https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/lib/gulp/json-to-vinyl.js#L45) file. It's intended to be a direct mirror for concatToJson.js.

<hr />

As for the issue where the output sourcemap refers to the intermediate file, this is something that should be handled by the compiler. I'm actually pretty shocked it's not. One of the SourceMap v3 spec authors is a long time compiler maintainer.

Can you file an issue for that here? https://github.com/google/closure-compiler/issues Make sure to post your repo case and you might also link to this discussion. I have bi-weekly face-to-face meetings with the core compiler team and I'll bring this up with them at our next meeting if the issue hasn't been responded to by then.

**Comment by rhendric** [comment]
Moved the relative path fix to `json-to-vinyl.js` as requested, and added a line to an existing test to check for it. I removed the input source map work; I'll wait to see what the compiler team has to say about the new issue. (I hadn't realized at first that this was an affiliated project—guess that helps explain why this is the best of the multiple Closure compiler interfaces on npm!) Thanks!

**Comment by ChadKillingsworth** [comment]
This looks great.

**Comment by brad4d** [comment]
@rhendric, I'm working to move this repository to the google/ project.
The only thing I'm lacking for that is a CLA signature from you.
Could you go to this website to fill one out?

https://cla.developers.google.com/clas

**Pull request merged**
